version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: knowledgehub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: knowledgehub
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret
    ports:
     - "3308:3306"  # host port 3307 → container 3306

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
